spring:
  # DATASOURCE CONFIGURATION
  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}

#  APP CONFIGURATION (INTERNAL)
app:
  base-url: /api/v1/os
  client:
    product:
      name: product-service
      url: http://localhost:7002/api/v1/ps