#  APP CONFIGURATION (INTERNAL)
app:
  base-url: /api/v1
  integration:
    product-service:
      api-prefix: /api/v1/products

spring:
  # Service Discovery configuration
  cloud:
    consul:
      discovery:
        metadata:
          basePath: /api/v1/orders;/api/v1/cart-items
