#  APP CONFIGURATION (INTERNAL)
app:
  base-url: /api/v1/products

spring:
  # Service Discovery configuration
  cloud:
    consul:
      discovery:
        metadata:
          basePath: ${app.base-url}
  cache:
    type: redis
  redis:
    host: "${REDIS_HOST:localhost}"
    port: "${REDIS_PORT:6379}"