spring:
  # DATASOURCE CONFIGURATION
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}

#  APP CONFIGURATION (INTERNAL)
app:
  base-url: /api/v1/ps
