spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    gateway:
      routes:

        # USER-SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/us/**

        # PRODUCT-SERVICE
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/ps/**

        # ORDER-SERVICE
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/os/**
