server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        register: true  # Optional, makes sure gateway is registered to Consul

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          include-expression: metadata['basePath'] != null
