spring:
  # DATASOURCE CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # SERVICE DISCOVERY CONFIGURATION (CONSUL)
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true

# ACTUATOR CONFIGURATION (ACTUATOR)
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

#  APP CONFIGURATION (INTERNAL)
app:
  base-url: /api/v1/ps