server:
  port: 0

spring:
  # DATASOURCE CONFIGURATION
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # SERVICE DISCOVERY CONFIGURATION (CONSUL)
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        prefer-ip-address: true

# ACTUATOR CONFIGURATION (ACTUATOR)
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always