server:
  port: 0

spring:

  # DATASOURCE CONFIGURATION
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # SERVICE DISCOVERY CONFIGURATION (CONSUL)
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: "${spring.application.name}:${server.port}"
        prefer-ip-address: true

  # DISABLING DEFAULT SECURITY
  security:
    user:
      name: none
      password: none

# ACTUATOR CONFIGURATION (ACTUATOR)
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always